"""add beach orientation to surf spots

Revision ID: f0162219623b
Revises: 76a75d83fdbd
Create Date: 2026-09-23 22:37:30.652645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0162219623b'
down_revision = '76a75d83fdbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surf_spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beach_orientation', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surf_spot', schema=None) as batch_op:
        batch_op.drop_column('beach_orientation')

    # ### end Alembic commands ###
